### ISSUE TITLE
New tag/release?

### ISSUE THREAD

**Issue by mattwthompson** [openforcefield/protein-ligand-benchmark#109]
There have been a few commits and several thousand lines of changes since the last release (0.2.1 May 2022). Are there plans to tag a new release at some point?

https://github.com/openforcefield/protein-ligand-benchmark/compare/0.2.1...main

**Comment by IAlibay** [comment]
@mattwthompson we are still working on getting things done for a new release, please see #106 

I would suggest speaking to David and James about this since it falls under ongoing collaobration work.

**Comment by mattwthompson** [comment]
Fair, my main need is being able to track where I yoinked a PDB from and I can just use a commit hash for that
