### ISSUE TITLE
Empty cofactors_crystalwater pdb files

### ISSUE THREAD

**Issue by ijpulidos** [openforcefield/protein-ligand-benchmark#15]
I am trying to run some automatic benchmarks for [our software](https://github.com/choderalab/perses) and I found out that there are some empty pdb files in the data, specifically the following:
* https://github.com/openforcefield/protein-ligand-benchmark/blob/master/data/2019-12-13_cmet/01_protein/crd/cofactors_crystalwater.pdb
* https://github.com/openforcefield/protein-ligand-benchmark/blob/master/data/2019-09-23_jnk1/01_protein/crd/cofactors_crystalwater.pdb
* https://github.com/openforcefield/protein-ligand-benchmark/blob/master/data/2019-12-13_cdk2/01_protein/crd/cofactors_crystalwater.pdb
* https://github.com/openforcefield/protein-ligand-benchmark/blob/master/data/2020-02-07_tyk2/01_protein/crd/cofactors_crystalwater.pdb

I presume this is unintended and something that has to be fixed. Thanks!

**Comment by ijpulidos** [comment]
CC ref https://github.com/choderalab/perses/issues/854

**Comment by ijpulidos** [comment]
So, I think maybe these examples/proteins don't really have or need these cofactors. Is that why these files are empty?

**Comment by dfhahn** [comment]
The empty `cofactors_crystalwater.pdb` are indeed intended, It means that for the specific targets with empty cofactors_crystalwater.pdb, no cofactors and water molecules were considered in the preparation. It might not be best practice to remove all cofactors/crystal waters, but the original publication did not consider any.

**Comment by dfhahn** [comment]
The README.md file was updated accordingly to clarify. 8c94c0d

**Comment by ijpulidos** [comment]
Thanks @dfhahn , sorry for the confusion.
