### ISSUE TITLE
Better advertise livecomms paper (and add to README)

### ISSUE THREAD

**Issue by IAlibay** [openforcefield/protein-ligand-benchmark#35]
Related in part to #26

It took us quite some time to find the link to the livecomms paper in yesterday's F@H alchemy call. It probably should be better signposted. @mikemhenry already has a PR open to add it to the README, it probably also should be placed at the forefront of the RTD docs.

**Comment by ppxasjsm** [comment]
Added link to arxiv paper and GitHub repo of the paper to Readme in this commit: 5355fc8c1a992a8d5481b3b49ed07b1a095bf288

**Comment by ppxasjsm** [comment]
Ah sorry I had missed this. It didn't look like it was placed prominently enough though to easily find it. Feel free to make changes to my commit though.

**Comment by mikemhenry** [comment]
If you didn't see it, then it wasn't placed prominently enough! Thanks :smile:
