### ISSUE TITLE
Fix Jnk1 charges

### ISSUE THREAD

**Issue by dfhahn** [openforcefield/protein-ligand-benchmark#37]
See suggested changes here: https://github.com/deGrootLab/pmx/commit/c8fb901f160901c7cc81f7f61580b61215e059d3

**Comment by dotsdl** [comment]
Should we remove Jnk1 entirely via #31?

**Comment by dotsdl** [comment]
If Jnk1 doesn't meet the requirements for:
- the dynamic range
- structural quality

then should probably be deprecated.

**Comment by jchodera** [comment]
cc #31, which discusses changing the X-ray structure to an alternate structure

**Comment by dotsdl** [comment]
FYI: May be dependent on #20.
