### ISSUE TITLE
Get RTD to build on PR builds

### ISSUE THREAD

**Issue by IAlibay** [openforcefield/protein-ligand-benchmark#38]
This would be quite useful going ahead for future work on docs.

**Comment by dotsdl** [comment]
@mikemhenry will take this on; @j-wags will check permission on RTD to ensure @mikemhenry has what he needs there to make changes.

**Comment by j-wags** [comment]
@mikemhenry  - @dfhahn just added us both as RTD admins for this repo (Thanks, David!)

**Comment by mikemhenry** [comment]
I've turned this on! Right now `main` fails to build since there are no commits on it, but that will be fixed soon!
