### ISSUE TITLE
Add CITATION.cff file to match the Contributors information

### ISSUE THREAD

**Issue by jchodera** [openforcefield/protein-ligand-benchmark#44]
We should add a [`CITATION.cff`](https://citation-file-format.github.io/) file to match the information from the [Contributors section](https://github.com/openforcefield/protein-ligand-benchmark#contributions).

**Comment by ijpulidos** [comment]
Do we want to have a doi zenodo reference for the citation? If that's the case, I cannot link to zenodo from my end.

**Comment by dotsdl** [comment]
Let's use the zenodo reference for this repo for the `doi` key in the CFF file. This will have to be updated with a commit *after* each release, since you'll need to wait for Zenodo to mint the new DOI.

**Comment by dotsdl** [comment]
From @mikemhenry: This is what I meant to link https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md#credit-redirection Where you can add "message: "If you use this software, please cite both the article from preferred-citation and the software itself.""
