### ISSUE TITLE
Add branch protection for main?

### ISSUE THREAD

**Issue by IAlibay** [openforcefield/protein-ligand-benchmark#49]
pinging @dotsdl and @j-wags 

There's quite a few of us looking to do maintenance on the repo now, and it probably is best to prevent us pushing directly to main?

**Comment by richardjgowers** [comment]
Seems like a good idea to me

**Comment by dotsdl** [comment]
Yes let's proceed with branch protection on `main`; shouldn't impact devops-based issues being resolved easily via @mikemhenry.

**Comment by dotsdl** [comment]
Added branch protection to `main`; changes to `main` can only be done via PR, and 1 approval is required for merge. 

I *did not* set required status checks for merge. If this is desired please reopen this issue and suggest which CI should be required (will have to change with time as Python versions we support do).
